### ISSUE TITLE
AssertionError when running LS_AMEGO.py with a specific video in Python

### ISSUE THREAD

**Issue by Davide-Marana** [gabrielegoletto/AMEGO#1]
I encountered an AssertionError while trying to run the Python script LS_AMEGO.py with a specific video of EPIC-KITHCENS (ID: P02_106). Below is the traceback:

> Traceback (most recent call last):
>   File "/path/to/AMEGO/LS_AMEGO.py", line 170, in <module>
>     processor.process()
>   File "/path/to/AMEGO/LS_AMEGO.py", line 123, in process
>     self.features_track[track_num] = self.extract_feat(track_boundaries)
>   File "/path/to/AMEGO/LS_AMEGO.py", line 111, in extract_feat
>     features.append(self.net(image.unsqueeze(0).cuda()))
>   File "path/to/anaconda3/envs/amego/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/path/to/.cache/torch/hub/facebookresearch_swag_main/models/vision_transformer.py", line 360, in forward
>     assert h == w == self.image_size
> AssertionError

It appears the error is related to the assert h == w == self.image_size line in the Vision Transformer model.
In this case, **h** and **w** are both _224_, while **self.image_size** is _512_.

Could you please advise on how to resolve this mismatch? Any guidance would be appreciated.

**Comment by gabrielegoletto** [comment]
Hello! I just added a patch including the transformations adopted by the SWAG models [ce683bd](https://github.com/gabrielegoletto/AMEGO/commit/ce683bdfe03ddc3bebaf1753092d9c8732ccaa4a). Let me know if you encounter other problems.
