### ISSUE TITLE
Would it be possible for you to share the datasets?

### ISSUE THREAD

**Issue by Code-kunkun** [gabrielegoletto/AMEGO#2]
Thank you for your excellent work! Would it be possible for you to share the datasets?

**Comment by gabrielegoletto** [comment]
Hi @Code-kunkun, thanks for your interest! The dataset we used is EPIC-KITCHENS, which can be downloaded [here](https://github.com/epic-kitchens/epic-kitchens-download-scripts). Regarding the proposed benchmark (AMB), all the questions can be found [here](https://github.com/gabrielegoletto/AMEGO/tree/main/AMB) along with the corresponding video_id from EPIC-KITCHENS.
