### ISSUE TITLE
AMEGO with non-EPIC videos

### ISSUE THREAD

**Issue by rui2016** [gabrielegoletto/AMEGO#3]
Hi, 

Does the current version work with non-EPIC videos out of the box? I did a quick try but it did not work. It seems multiple places are not set properly for customized videos. 

Thanks in advance.

**Comment by gabrielegoletto** [comment]
Hello @rui2016, and thanks for your interest! I’ve released a [script](https://github.com/gabrielegoletto/AMEGO/blob/main/prepare_video.sh) that simplifies the process of precomputing FlowFormer optical flow and extracting hand-object bounding boxes. Additionally, I’ve added the fps input parameter, enabling AMEGO extraction on new videos. You can now easily run AMEGO on customized videos by executing the bash command and providing the video path and fps as parameters (both for the bash command and when launching HOI_AMEGO.py and LS_AMEGO.py), as outlined in the README. Let me know if you encounter any issues!
